######################################################################################
# A default configuration that will be loaded for all jupyter books
# See the documentation for help and more options: 
# https://jupyterbook.org/customize/config.html

#######################################################################################
# Book settings
title                       : Introduction to deep learning for particle physicists  # The title of the book. Will be placed in the left navbar.
author                      : Jim Pivarski  # The author of the book
copyright                   : "2024"  # Copyright year to be placed in the footer
logo                        : "img/book-logo.svg"

# Force re-execution of notebooks on each build.
# See https://jupyterbook.org/content/execute.html
execute:
  execute_notebooks: force
  allow_errors: false

# Define the name of the latex output file for PDF builds
latex:
  latex_documents:
    targetname: book.tex

# Add a bibtex file so that we can create citations
bibtex_bibfiles:
  - references.bib

# Information about where the book exists on the web
repository:
  url: https://github.com/hsf-training/deep-learning-intro-for-hep  # Online location of your book
  path_to_book: deep-learning-intro-for-hep  # Optional path to your book, relative to the repository root
  branch: main  # Which branch of the repository should be used when creating links (optional)

# Add GitHub buttons to your book
# See https://jupyterbook.org/customize/config.html#add-a-link-to-your-repository
html:
  use_issues_button: true
  use_repository_button: true
  analytics:
    plausible_analytics_domain: hepsoftwarefoundation.org
    plausible_analytics_url: https://views.scientific-python.org/js/script.js

parse:
  myst_enable_extensions:
    - attrs_inline
    - dollarmath
    - smartquotes
  myst_heading_anchors: 3

sphinx:
  config:
    html_extra_path:
      - "img/tensorflow-playground.png"
      - "img/ups-and-downs-of-ai-3-overlay.png"
      - "img/distill-momentum.png"
      - "img/playground-solution-circle-1.png"
      - "img/playground-solution-circle-2.png"
      - "img/ridiculously-overfitted.png"
      - "img/better-boy-wolf-1.jpg"
      - "img/better-boy-wolf-2.jpg"
      - "img/better-boy-wolf-3.jpg"
      - "img/better-boy-wolf-4.jpg"
    nb_execution_show_tb: true
