name: deep-learning-intro-for-hep

channels:
  - conda-forge

dependencies:
  - python=3.11

  # infrastructure (you won't need these)
  - jupyter-book
  - jupytext
  - ghp-import

  # packages we'll use
  - numpy
  - matplotlib
  - pandas
  - iminuit
  - scikit-learn
  - fastparquet
  - pytorch-cpu  # this is `torch` in pip

  # used in very few sections (optional)
  - h5py
  - scipy
  - uproot
  - pip:
    - torch_geometric
