name: deep-learning-intro-for-hep

channels:
  - conda-forge

dependencies:
  - python=3.11

  # infrastructure (you won't need these)
  - jupyter-book
  - ghp-import

  # packages we'll use
  - numpy
  - matplotlib
  - pandas
  - iminuit
  - scikit-learn
  - h5py
  - scipy
  - awkward
  - pytorch-cpu  # `torch` in pip
